package aplicacion.modelo.dominio;
// Generated 20/06/2019 19:14:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *Categorias generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idcategoria;
     private String nombre;
     private String descripcion;
     private Boolean estado;
     private Set productoses = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nombre, String descripcion, Boolean estado, Set productoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.productoses = productoses;
    }
   
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


